apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "DevCheckOps007"

  links:
    - url: https://github.com/RohanAwasthi/DevCheckOps007
      title: "DevCheckOps007"
      icon: code

  labels:
    system: web-apps
    environmentname: devops007-env

  tags:
    - python
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-DevCheckOps007'
    github.com/project-slug: RohanAwasthi/DevCheckOps007
    dev.azure.com/project: 'SDAFY24'
    dev.azure.com/build-definition: 'ey-org.devexplatform'
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/ebs-sample-python-application
    sonarqube.org/project-key: 'python-app/aws-elb-python'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "Developers"
